import { Inter } from "next/font/google";
import "./globals.css";
import LoginButton from "./component/LoginButton";
import LogoutButton from "./LogoutButton";
import { getServerSession } from "next-auth";
import { AuthOptions } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import MetaMask from "./MetaMask";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {session ? (
          <span>
            {session.user.name} <LogoutButton />{" "}
          </span>
        ) : (
          <LoginButton></LoginButton>
        )} */}
        <MetaMask session={session}></MetaMask>

        {children}
      </body>
    </html>
  );
}
